AllCops:
  NewCops: enable
  TargetRubyVersion: '2.3' # lowest common limit of newrelic_rpm and hanami-controller

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/FileName:
  Exclude:
    - 'lib/newrelic-hanami.rb'
